
export const LOAD_LOCATION = 'LOAD_LOCATION';
export const UPDATE_CHARACTER = 'UPDATE_CHARACTER';
export const CHARACTER_UPDATE = 'CHARACTER_UPDATE';
export const CHARACTER_LEAVE = 'CHARACTER_LEAVE';
export const CHARACTER_JOIN = 'CHARACTER_JOIN';
export const CHANGE_LOCATION = 'CHANGE_LOCATION';
export const REQUEST_LOCATION_CHANGE = 'REQUEST_LOCATION_CHANGE';
export const LOAD_GAME = 'LOAD_GAME';