
export const MESSAGE_TYPES = {
  PRIVATE: 'PRIVATE',
  GROUP: 'GROUP',
  CLAN: 'CLAN',
  LOCAL: 'LOCAL',
  GLOBAL: 'GLOBAL'
}

export const CHARACTER_STATUS = {
  IDLE: 'IDLE',
  FIGHTING: 'FIGHTING',
  TRADING: 'TRADING',
  ASLEEP: 'ASLEEP'
}

export const MOB_STATUS = {
  IDLE: 'IDLE',
  FIGHTING: 'FIGHTING',
  RESPAWNING: 'RESPAWNING'
}

export const FIGHT_ACTION_TYPE = {
  STEP_AHEAD: 'STEP_AHEAD',
  BASIC_ATTACK: 'BASIC_ATTACK',
  USE_ABILITY: 'USE_ABILITY'
}