
export const MESSAGE_TYPES = {
  PRIVATE: 'PRIVATE',
  GROUP: 'GROUP',
  CLAN: 'CLAN',
  LOCAL: 'LOCAL',
  GLOBAL: 'GLOBAL'
}

export const CHARACTER_STATUS = {
  IDLE: 'IDLE',
  FIGHTING: 'FIGHTING',
  TRADING: 'TRADING',
  ASLEEP: 'ASLEEP'
}